version: 0.2

phases:
  install:
    commands:
      # Update libs
      - apt-get update
      - cd app
      # Headless Chrome
      - apt-get install -y fonts-liberation libasound2 libnspr4 libnss3 libx11-xcb1 xdg-utils libxss1 libappindicator1 libindicator7
      - ewget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      - dpkg -i google-chrome*.deb
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build:ci
      - npm run test:ci
  post_build:
    commands:
      - aws s3 sync ./dist/angular-devops s3://ui-bucket-develop --acl 'public-read' --delete
      #- aws s3 cp ./dist/moxa-ui s3://$MoxaUiBucket_name --recursive --acl public-read-write
      #- aws s3 sync ./dist/ui-moxa s3://$MoxaUiBucket_name  --acl 'public-read' --delete
artifacts:
   files:
     - '**/*'
