version: 0.2

phases:
  install:
    commands:
      # Update libs
      - apt-get update
      - cd app
      # Headless Chrome for testing
      #- apt-get install -y fonts-liberation libasound2 libnspr4 libnss3 libx11-xcb1 xdg-utils libxss1 libappindicator1 libindicator7
      #- wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      #- dpkg -i google-chrome*.deb
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build:ci
      - npm run test:ci
  post_build:
    commands:
      # Copy build artifacts to S3 bucket
      - aws s3 sync ./dist/angular-devops s3://$UiBucket_name --acl 'public-read' --delete
   files:
     - '**/*'
