   
version: 0.2
env:
  variables:
    UiBucket_name: $UiBucket_name
phases:
  install:
    commands:
      # Update libs
      - apt-get update
      - cd app
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build:ci
artifacts:
   files:
     - '**/*'
