   
version: 0.2
env:
  variables:
    UiBucket_name: $UiBucket_name
phases:
  install:
    commands:
      # Update libs
      - apt-get update
  pre_build:
    commands:
      - echo "Running unit test"
      
  build:
    commands:
      - #npm test
artifacts:
   files:
     - '**/*'
