on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags' 
env:
  custom: 'check for env'
    
name: Prod- deploy

jobs:
  build:
    name: Build-step
    runs-on: ubuntu-latest
    if: github.actor == 'Faithtosin'
    environment: development

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        repository: Faithtosin/honig
        ref: master
        token: ${{ secrets.TOKEN }}
    - name: check files
      run: ls -la

  call-workflow-passing-data:
    uses: honig/.github/workflows/template.yml@master
    with:
      username: Faith
      env: development
   
