on:
  workflow_dispatch:
    inputs:
      username:
        description: 'Username'     
        required: true
        default: 'buildspec.yaml'
      env:
        description: 'env' 
        required: true
        default: 'development'
env:
  custom: "custon env"
    
name: Caller Priv Workflow refresh

jobs:
  build:
    name: Build-step
    runs-on: ubuntu-latest
    needs: call-workflow-passing-data
    if: github.actor == 'Faithtosin'

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        repository: Faithtosin/honig
        ref: master
        token: ${{ secrets.TOKEN }}
    - name: check files
      run: ls -la

  call-workflow-passing-data:
    uses: Faithtosin/honig/.github/workflows/codebuild.yml@master
    secrets:
      access_key_id: ${{ secrets.ACCESS_KEY_ID }}
      secret_access_key: ${{ secrets.SECRET_ACCESS_KEY }}
    with:
      username: ${{ github.event.inputs.username }}
      env: ${{ fromJSON(env.custom) }}
      #env: ${{ env.custom }}
