on:
  workflow_dispatch:
    inputs:
      username:
        description: 'Username'     
        required: true
        default: 'warning'
      env:
        description: 'env' 
        required: true
        default: 'development'
env:
  custom: 'check for env'
    
name: Caller Priv Workflow

jobs:
  build:
    name: Build-step
    runs-on: ubuntu-latest
    needs: call-workflow-passing-data
    if: github.actor == 'Faithtosin'

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        repository: Faithtosin/honig
        ref: master
        token: ${{ secrets.TOKEN }}
    - name: check files
      run: ls -la

  call-workflow-passing-data:
    uses: Faithtosin/honig/.github/workflows/template.yml@master
    with:
      username: ${{ github.event.inputs.username }}
      env: ${{ github.event.inputs.env }}
