on:
  workflow_dispatch:

    
name: Caller Workflow

jobs:
  call-workflow:
    uses: Faithtosin/reusable-workflows/.github/workflows/called.yml@master
    secrets: 
      ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
      SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
      TOKEN: ${{ secrets.TOKEN }}
      UIBUCKET_NAME: ${{ secrets.DEV_UIBUCKET_NAME }}
      CLOUDFRONT_ID: ${{ secrets.DEV_CLOUDFRONT_ID }}
    with:
      ENV: dev
   
