on:
  workflow_dispatch:
    inputs:
      username:
        description: 'Log level'     
        required: true
        default: 'warning'
      env:
        description: 'Test scenario tags' 
        required: true
        default: 'development'
env:
  custom: 'check for env'
    
name: Caller Workflow

jobs:
  build:
    name: Build-step
    runs-on: ubuntu-latest
    needs: call-workflow-passing-data
    if: github.actor == 'Faithtosin'
    environment: development

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        repository: Faithtosin/honig
        ref: master
        token: ${{ secrets.TOKEN }}
    - name: check files
      run: ls -la

  call-workflow-passing-data:
    uses: Faithtosin/KinesisTool/.github/workflows/called-workflow.yml@master
    with:
      username: ${{ inputs.username }}
      env: ${{ inputs.env }}
   
