on:
  pull_request:
    branches:
      - master
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags' 
env:
  custom: 'check for env'
    
name: Prod- deploy

jobs:
  build:
    name: Build-step
    runs-on: ubuntu-latest
    if: github.actor == 'Faithtosin'
    environment: development

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        repository: Faithtosin/honig
        ref: master
        token: ${{ secrets.TOKEN }}
    - name: check files
      run: ls -la

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Run CodeBuild
      uses: aws-actions/aws-codebuild-run-build@v1
      with:
        project-name: codebuild-github-action
        buildspec-override: buildspec.yaml
        env-vars-for-codebuild: |
          custom,
          requester,
          event-name
      env:
        custom: ${{ env.custom }}
        requester: ${{ github.actor }}
        event-name: ${{ github.event_name }}
