on:
  pull_request:
    branches:
      - master
  workflow_dispatch:
    inputs:
      input1:
        description: 'first input'     
        required: true
        default: 'warning'
      tags:
        description: 'second input' 
env:
  ENV1: 'Workflow_env'
    
name: PR-Pipeline

jobs:
  test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Run CodeBuild
      uses: aws-actions/aws-codebuild-run-build@v1
      with:
        project-name: codebuild-github-action
        buildspec-override: .github/workflows/buildspecs/codebuild-test.yaml

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: test
    if: "!failure() && !cancelled()"
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
        aws-region: us-east-1
      
    - name: Run CodeBuild
      uses: aws-actions/aws-codebuild-run-build@v1
      with:
        project-name: codebuild-github-action
        buildspec-override: .github/workflows/buildspecs/codebuild-build.yaml

  
  deploy-dev:
    name: Deploy to Dev
    runs-on: ubuntu-latest
    needs: build
    if: "!failure() && !cancelled()"
    environment: dev

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      #Clone another repository, no Token if public
      # with:
      #   repository: Faithtosin/honig
      #   ref: master
      #   token: ${{ secrets.TOKEN }}
    - name: check files
      run: ls -la

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Run CodeBuild
      uses: aws-actions/aws-codebuild-run-build@v1
      with:
        project-name: codebuild-github-action
        buildspec-override: .github/workflows/buildspecs/codebuild-deploy.yaml
        env-vars-for-codebuild: |
          custom,
          Pull_Request_Number,
          UiBucket_name,
          CLOUDFRONT_ID
      env:
        ENV_VAR: ${{ env.ENV1 }}
        requester: ${{ github.actor }}
        event-name: ${{ github.event_name }}
        event-number: ${{ github.event.number  }}
        Pull_Request_Number: ${{ github.event.pull_request.number }}
        UiBucket_name: ${{ secrets.DEV_UIBUCKET_NAME }}
        CLOUDFRONT_ID: ${{ secrets.DEV_CLOUDFRONT_ID }}
